# -*- coding: utf-8 -*-
"""Doctor_visualization.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g9LHUgLL9pHhyIMSvDu98lYM-qeAiAfa
"""

# Doctor_visualization.py


class Visualization:
  def scatter_plot_vis(column1,column2):
    plt.scatter(df[column1], df[column2])
    plt.title('Scatter Plot of '+column1+' vs '+column2+'')
    plt.xlabel(column1)
    plt.ylabel(column2)
    plt.show()
    """
    Encodes categorical columns in a DataFrame using LabelEncoder.

    Parameters:
    - df (pandas.DataFrame): The input DataFrame containing categorical columns to be encoded.

    Returns:
    - pandas.DataFrame: A new DataFrame with encoded numerical values for categorical columns.

    """


  def histogram_vis(column1,column2):
    plt.hist(df[column1], bins=20, color='skyblue', edgecolor='black')
    plt.title('hisogram  Plot of '+column1+' and '+column2+'')
    plt.xlabel(column1)
    plt.ylabel(column2)
    plt.show()

    """
    Creates and displays a histogram plot for two columns in a DataFrame.

    Parameters:
    - column1 (str): Name of the first column for the histogram.
    - column2 (str): Name of the second column for the histogram.

    Returns:
    - None

    """

